
public class Main {

	public static void main(String[] args) {
		ForcaBruta forcaBruta = new ForcaBruta();;
		KMP kmp = new KMP();
		
		String txt = getText();
		System.out.println("==================Algoritmo Força Bruta================");
		String pat = "TATATAAGAAAAAAG";
		System.out.println("Padrão procurado: TATATAAGAAAAAAG");
		forcaBruta.getForcaBruta(pat, txt);
		
		System.out.println();
		pat = "AGACTCTG";
		System.out.println("Padrão procurado: AGACTCTG");
		forcaBruta.getForcaBruta(pat, txt);
		
		System.out.println();
		pat = "GAGAGCGG";
		System.out.println("Padrão procurado: GAGAGCGG");
		forcaBruta.getForcaBruta(pat, txt);
		
		System.out.println();
		pat = "TCCTCCCAC";
		System.out.println("Padrão procurado: TCCTCCCAC");
		forcaBruta.getForcaBruta(pat, txt);
		
		System.out.println();
		System.out.println("======================Algoritmo KMP====================");
		pat = "TATATAAGAAAAAAG";
		System.out.println("Padrão procurado: TATATAAGAAAAAAG");
		kmp.getKMP(pat, txt);

		System.out.println();
		pat = "AGACTCTG";
		System.out.println("Padrão procurado: AGACTCTG");
		kmp.getKMP(pat, txt);

		System.out.println();
		pat = "GAGAGCGG";
		System.out.println("Padrão procurado: GAGAGCGG");
		kmp.getKMP(pat, txt);

		System.out.println();
		pat = "TCCTCCCAC";
		System.out.println("Padrão procurado: TCCTCCCAC");
		kmp.getKMP(pat, txt);
	}
	
	public static String getText() {
		String str = "AGGCTTTTTGGTACCACAAACGTAGCGAGCATGAACTTTTCCTAAATTAAGACATTTACGACCTG"
				+ "GTCAGATGCGAATCAATAATGAAATGGCCATGCAAAATTCTAGACACAACAAGCGCTTAAGAGCC"
				+ "GCCACGGGGAATACCGCAACGGTAAATGGGTCTTCAGAGGAGACCATAGACTTCATGACTGCAGA"
				+ "TACCCGACTTGAGATTAGAATGAATCATTTCCAAGCATCCTAATTGAGTTGTGGCCACGCTGGCA"
				+ "GGCCGAAATATTAGCAGACGCCTTGTCGATGTCCAAGTTCTAGTCTGAGTGTTGGTCTGGGAGTA"
				+ "GGTCTGGCTTTTGGGCTTGAGGTGTGAGACTACTTAGCCGGGCCAACTAAGCGGGGCCAAACGGC"
				+ "AACGATTAGTCGCAGGCTTTGTAGGAGGAAGTGGACGAAGTCTAAGACTAAGGGCCATTTATCAA"
				+ "GAGCTGCTCGTGTCTCGTCTCTTTGGGCAAATTAACAGTTCCCCAACTGGTACCCAATTGGCCTT"
				+ "TACAGAGTGGCTAACGGGTGCTGGGCTCCCACTTTAATTGCTCCATCGATGTTCTCACACCGAAA"
				+ "GTGTTATTAGAAGTTGGAGTCAGCAGTCTGAAATTTTGAATGTAGTTCTCTGGGTCAATGCGACC"
				+ "ACCTGAACTAATCGAAGCCACATCGAGCGGAGCACGCGCCCAGTCAATGAGCTTTCACAAAATAA"
				+ "TTCAGCAATGCTGCACGCACTCGGAATGTGGCTCCAAGATCTTGACAAGAAGACTTGGCTTGCTC"
				+ "CAAAGCCAAATGAATTCGATTGGGGTGTGACAAGAACCAAAGCGATCTTCAACCTGCACCTTAAG"
				+ "GGTGGACATGCATCTGTGAGAACTCTTACTCGAGCTGAACCTCACGTTCCACGGCAAAGGGTTCC"
				+ "AGGTTCCAGTTCCATAAAACACAATGGAGCATCGCCGTCTCAGTGCTATTGTTCTATCGATGGCC"
				+ "GCAGCTTGCAAATTTTCGGCTGCTTTAATGTTTATTCATGAATTCATTAATTCGAGCTGCTCGTG"
				+ "GCCGCAGGTCGTGTAGTCTTAGAACATTTTCATGTTCAGCAGAGCATTTTGTTTTTACGACAACA"
				+ "TTGGAGGAAACGAAGCCATCGTCGTCTTGGTCGTCAGAATGGAACAGGATGCGGCTCTGCAGGCT"
				+ "TCGATGGCAACTTTGGCCCGGACTCCGACTTTTGGACTCCTGTCATGTGGAACTGGCATAATAAA"
				+ "AATGCTAGCAGCGCTTTTCGGTGGCGGCGGCGGTGGCCCCGTTGTGCTGTTAATGTTGGCATTTA"
				+ "TATGCCATAGAGTTTTTAATGCGATTAGCGCAATTAATCGCCCGTCGCCGAAGCGTTCAAATTGC"
				+ "AGATTTTTGTTCTGTTGGCGGAAGTTGCCATGGCGTGCAAACGGTCGTTCAGGCAGTGCCCATCG"
				+ "ATTGCCGCTGCCCATTAATAATCCCAGTCGAGATGTCGAAAGGAATGCTGCGGGTTCGGTCGAAA"
				+ "CCAAGTACAACCAACTCGACCTGAAAGTGAGAGTTGCCCCGGGACACCCAACCGCTCTGACCCAC"
				+ "TCGATTTGAATCCGTGCGTGGATGCAAACAAACAAATCGGTGATTTATGCTCGTCGAGGAAAGCA"
				+ "TGTGAAAAGTGCCGAACCTGGTGCACAGCTCCTCCCACTTCACTTTCGTGTGGGAAAGTGCTCAA"
				+ "AACGGGGCGGGAGCTCAGCCCTGTTGATGATGGATTCGAGACCCCCGTGCAATTACTGCCGCTTA"
				+ "GCATAAATCGCGCGACCCAACCGCTCTGACCCACATTAATTCGCCGCAGAACACTGTGCCCAGAG"
				+ "CCAGAGCGGAAATTAACTAAGCTCCAATCTGGCAAGACTCCGTCGATTGCACTCAGCAAAAATGG"
				+ "GGCTTTCTATATAAGAAAAAAGTGCGATTACATCCTAAACACATCACGCAATACAACCCTTGTAC"
				+ "CCGAAGTAATAAGCTGTAGCTGAGACTCTGCGATTCAATGCATTTGCATAATATTGAAGGGTAAT"
				+ "TTCCAATGAATTTCTTTCGGTGTACAAAATAGAAGCCGCTGCGCAGCCGCAGAACACTGTGCAAA"
				+ "TAGAGTTTTTAATGCGATTAGCGCAATTAATCGCCCGTCGCCGAAGCGTTCAAATTGCAGATTTT"
				+ "TGTTCTGTTGGCGGAAGTTGCCATGGCGTGCAAACGGTCGTTCAGGCAGTGCCCATCGATTGCCG"
				+ "CTGCCCATTAATAATCCCAGTCGAGATGTCGAAAGGAATGCTGCGGGTTCGGTCGAAACCAAGTA"
				+ "CAACCAACTCGACCTGAAAGTGAGAGTTGCCCCGGGACAGCTGAAGCTGAATCGATTTGAATCCG"
				+ "TGCGTGGATGCAAACAAACAAATCGGTGATTTATGCTCGTCGAGGAAAGCATGTGAAAAGTGCCG"
				+ "AACCTGGTGCACAGCTCCTCCCACTTCACTTTCGTGTGGGAAAGTGCTCAAAACGGGGCGGGAGC"
				+ "TCAGCCCTGTTGATGATGGATTCGAGACCCCCGTGCAATTACTGCCGCTTAGCATAAATCGCGCG"
				+ "GGAAATTAACTAAGCTCCAATCTGGCAAGACTCCGTCGATTGCACTCAGCAAAAATGGGGCTTTC"
				+ "TATATAAGAAAAAAGTGCGATTACATCCTAAACACATCACGCAATACAACCCTTGTACCCGAAGT"
				+ "AATAAGCTGTAGCTGAGACTCTGCGATTCAATGCATTTGCATAATATTGAAGGGTAATTTCCAAT"
				+ "GAATTTCTTTCGGTGTACAAAATAGAAGCCGCTGCGCACGGGCCACTAGTTCGCTCTATAAGTCA"
				+ "CCGCCGCGGTGCCGGTCTGGGCTTTGTTACATATTATTTATTGTGTCGGTGCTGCACCGAGGAAA"
				+ "CCAAGGCACCGCGCTTAGCTTCCACCATGCTCCTCCATCCGACTGAAACGAATCCCGTGGGCGTT"
				+ "TAACGGCATCTCGTAAGTTGCATATTTGCCGGCAAGTCAAAAATTCGTGTGCACAGCCTGGGTAT"
				+ "CGCTTAATGGGTGTGGGTGTCTGACTCGCAGCTCCTTGGTTGCGGAATGAGTAGTGAAGGTCACA"
				+ "ATTAATTCGCCGCAGAACACTGTGCCCAGAGCCAGAGCGGAAATTAACTAAGCTCCAATCTGGCA"
				+ "AGACTCCGTCGATTGCACTCAGCAAAAATGGGGCTTTCTATATAAGAAAAAAGTGCGATTACATC"
				+ "CTAAACACATCACGCAATACAACCCTTGTACCCGAAGTAATAAGCTGTAGCTGAGACTCTGCGAT"
				+ "TCAATGCATTTGCATAATATTGAAGGGTAATTTCCAATGAATTTCTTTCGGTGTACAAAATAGAA"
				+ "GCCGCTGCGCACGGGCCACTAGTTCGCTCTATAAGTCACCGCCGCGGTGCCGGTCTGGGCTTTGT"
				+ "TACATATTATTTATTGTGTCGGTGCTGCACCGAGGAAACCAAGGCACCGCGCTTAGCTTCCACCA"
				+ "TGCTCCTCCATCCGACTGAAACGAATCCCGTGGGCGTTTAACGGCATCTCGTAAGTTGCATATTT"
				+ "GCCGGCAAGTCAAAAATTCGTGTGCACAGCCTGGGTATCGCTTAACTGACTCGCAGCTCCTTGGT"
				+ "TGCGGGTTTACGGGATATCGGTGGACCATATCGGTGGCAATAAAATTATGTAAAGAGCGTTTTTT"
				+ "TTTTTTTTTTTTTTTTTGGCGGCAACAAGTGTCGATGCAAGGGAGTGGGCGCTTTCAGCTCCGGT"
				+ "ACAAACAAGTAAATGCAATTTGTGGCTCCATTTATGCGATGCTGGGCCACAGGCGGTAATTTGTA"
				+ "TAAGTCACAACAAGGGATTACAAGGGTTACAAGTCTAGCCAAAAAATTTTACAGTTCAAGAAAGC"
				+ "TCCATTGATTTATTTTGAATTGAGAGCGGTTTAAATGCTGTCATAAGTAGCTTAATCCAATAAAC"
				+ "GGAGCCCATTATAACGAGACTTTCGTCTCACTTTCATTAGCTCGGGTGTGACAAGTTCCCATGTG"
				+ "AGCGACCTAAGCCCCAGGAAATCGGCTTATGGGCCATTTTATACGGGTCCGAGTCCGAGAACGAG";

		return str;
	}

}
